hydra:
  job:
    name: ${backbone.name}_${backbone.topk}
  run:
    dir: /Users/gen/workspace/boatse-rag-agents/output/lca/w_extracted/${hydra:job.name}${run_suffix}
  job_logging:
    root:
      handlers: [console, file]
backbone:
  _target_: src.baselines.backbones.bm25.bm25_retriever.BM25Backbone
  name: bm25-retriever-qwen3
  data_path: ${data_source.repos_dir}
  topk: 0
  percent: 100 # retrieve the max so we can derive smaller percentages
  k1: 0.9
  b: 0.4

data_source:
  _target_: src.baselines.data_sources.hf_data_source.HFDataSource
  repos_dir: /Volumes/T9/lca/cloned_repos_test 
  cache_dir: null
  hub_name: tiginamaria/bug-localization
  configs:
    - py
    - java
    - kt
  split: test

reindex: False
run_suffix: "__1"
extracted_info_dir: /Users/gen/workspace/boatse-rag-agents/bug_localization/output/lca/extracted/qwen-agent_qwen2.5-coder-32b-16k_extracting__1