hydra:
  job:
    name: ${backbone.name}_${backbone.model_name}_${backbone.experiment}
  run:
    dir: /Users/gen/workspace/boatse-rag-agents/bug_localization/output/swe/extracted/${hydra:job.name}${run_suffix}
  job_logging:
    root:
      handlers: [console, file]
backbone:
  # Switch to a backbone implementation that uses the Ollama API.
  _target_: src.baselines.backbones.agent.info_extraction_backbone.InfoExtractionBackbone
  name: swe-agent
  # This is the model identifier as recognized by Ollama.
  model_name: qwen3-32b-16k

  prompt:
    _target_: src.baselines.backbones.agent.prompts.agent_context_prompt.AgentContextPrompt
  
  experiment: extracting

data_source:
  _target_: src.baselines.data_sources.swe_bench_data_source.SWEDataSource 
  repos_dir: /Users/gen/workspace/SWE-bench/swebench/inference/repos_lite
  cache_dir: null
  hub_name: /Users/gen/workspace/SWE-bench/swebench/inference/hf_datasets/SWE-Bench_Lite 
  split: test

run_suffix: ""
